[build]
  command = "pip install -r netlify/functions/requirements.txt" # Comando de construcción explícito
  environment = { PYTHON_VERSION = "3.9" } # Forzamos la versión de Python 3.9 para el entorno de construcción

[functions]
  directory = "netlify/functions"
  node_bundler = "none" # Asegura que no se use un bundler de Node.js para las funciones Python
