[build]
  command = "pip install -r netlify/functions/requirements.txt" # Comando de construcción explícito
  environment = { PYTHON_VERSION = "3.9" } # Forzamos la versión de Python 3.9 para el entorno de construcción

[functions]
  directory = "netlify/functions"
  # timeout = 10 # segundos (el valor por defecto es 10 segundos, máx 26)

  # Configuración específica para funciones Python
  [functions.python]
    zip_artifacts = false # Descomentado: Le dice a Netlify que no use un "zip" para el empaquetado.
