[functions]
  directory = "netlify/functions"
  # Puedes especificar el tiempo de espera (timeout) si tus funciones tardan mucho
  # timeout = 10 # segundos (el valor por defecto es 10 segundos, máx 26)
  # Puedes especificar el entorno de ejecución de Python si es necesario
  # python_version = "3.9" 