[build]
  # Sin comandos de build globales para la instalación de dependencias.
  # Mantener esto si no usas un comando de build global para tu sitio (por ejemplo, si es solo HTML/CSS/JS estático)
  # Si tu sitio web principal tiene un comando de build (ej. "npm run build"), DEBES añadirlo aquí:
  # command = "npm run build"
  publish = "dist" # Si tu sitio genera archivos estáticos en una carpeta 'dist', si no, cambia a la carpeta correcta (ej. ".")

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild" # Nueva línea: Forzar el bundler esbuild para las funciones

[build.environment]
  NODE_VERSION = "16" # Nueva línea: Forzar Node.js 16 para el entorno de build y ejecución de funciones

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[[plugins]] # Nuevo bloque de plugin
  package = "netlify-plugin-inline-functions-env"
  [plugins.inputs]
    # Puedes dejar esto vacío por ahora